# menu
menu:
  Home: .
  Archives: archives # 归档
  Categories: categories # 分类
  Tags: tags # 标签
  Links: links # 友链
  About: about # 关于

# Enable/Disable menu icons
menu_icons:
  enable: true # 是否启用导航菜单图标
  home: icon-home-fill
  archives: icon-archives-fill
  categories: icon-folder
  tags: icon-tags
  repository: icon-project
  books: icon-book-fill
  links: icon-friendship
  about: icon-cup-fill

# rss
rss: /atom.xml

# Site
site:
  logo:
    enabled: true
    width: 40
    height: 40
    url: /images/common/avatar.jpg
  title: 采菊东篱 # 页面title
  favicon: /favicon.png
  board: <p>好记性，不如烂笔头</p> # 站点公告
  copyright: true # 底部版权信息

# config
config:
  skin: theme-purple # 主题颜色 theme-black theme-blue theme-green theme-purple
  layout: main-center # 布局方式 main-left main-center main-right
  toc: true # 是否开启文章章节目录导航
  menu_highlight: true # 是否开启当前菜单高亮显示
  thumbnail: false # enable posts thumbnail, options: true, false
  excerpt_link: Read More

# Pagination
pagination:
  number: true
  prev:
    alwayShow: true
  next:
    alwayShow: true

# Sidebar
sidebar: right
widgets:
  - board
  - tagcloud
  - category
  # - archive
  # - tag
  - recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
  - category
  - tagcloud
  - archive

# widget behavior
archive_type: "monthly"
show_count: true

# Fancybox
fancybox: true

# Search
search:
  insight: true # you need to install `hexo-generator-json-content` before using Insight Search
  baidu: false # you need to disable other search engines to use Baidu search

# Donate
donate:
  enable: false
  # 微信打赏
  wechatpay:
    qrcode: images/donate/wechatpayimg.png
    title: 微信支付
  # 支付宝打赏
  alipay:
    qrcode: images/donate/alipayimg.png
    title: 支付宝

# Share
# weibo,qq,qzone,wechat,tencent,douban,diandian,facebook,twitter,google,linkedin
share:
  enable: false # 是否启用分享
  sites: weibo,qq,wechat # PC端显示的分享图标
  mobile_sites: weibo,qq,qzone # 移动端显示的分享图标

# Github
github:
  username: lesterlaucn # github username

# Comment
# Gitment
# Introduction: https://imsun.net/posts/gitment-introduction/
comment:
  type: disqus # 启用哪种评论系统
  disqus: cai-ju-dong-li # enter disqus shortname here
  youyan:
    uid: 1783844 # enter youyan uid
  livere:
    uid: # enter youyan uid
  gitment:
    githubID: tenstone
    repo: blog.beyhub
    ClientID:
    ClientSecret:
    lazy: true
  gitalk: # gitalk. https://gitalk.github.io/
    owner: tenstone #必须. GitHub repository 所有者，可以是个人或者组织。
    admin: tenstone #必须. GitHub repository 的所有者和合作者 (对这个 repository 有写权限的用户)。
    repo: blog.beyhub #必须. GitHub repository.
    ClientID: #必须. GitHub Application Client ID.
    ClientSecret: #必须. GitHub Application Client Secret.
douban:
  user: # 豆瓣用户名
  start: 0 # 从哪一条记录开始
  count: 100 # 获取豆瓣书单数据条数
  apikey: # 豆瓣apikey

# PV
pv:
  busuanzi:
    enable: false # 不蒜子统计
  leancloud:
    enable: false # leancloud统计
    app_id: # leancloud <AppID>
    app_key: # leancloud <AppKey>

# wordcount
postCount:
  enable: true
  wordcount: true # 文章字数统计
  min2read: true # 阅读时长预计

# Plugins
plugins:
  google_analytics: # enter the tracking ID for your Google Analytics
  google_site_verification: # enter Google site verification code
  baidu_analytics: # enter Baidu Analytics hash key
  tencent_analytics:

# Miscellaneous
twitter:
google_plus:
fb_admins:
fb_app_id:

# profile
profile:
  enabled: true # Whether to show profile bar
  avatar: /images/avatar.jpg
  gravatar: # Gravatar email address, if you enable Gravatar, your avatar config will be overriden
  author: Lester Lau
  author_title: 采菊东篱下，悠然见南山
  author_description:
  location: NanJing, China
  follow: https://github.com/lesterlaucn
  # Social Links
  social:
    links:
      github: https://github.com/lesterlaucn
      weibo: http://weibo.com/lyc90
      twitter: https://twitter.com/lesterlaucn
      # facebook: /
      # dribbble: /
      rss: atom.xml
    link_tooltip: true # enable the social link tooltip, options: true, false
  # My Skills
  skills:
    Java: ★★★★★
    Golang: ★★★☆☆
    Python: ★★★☆☆
    Kubernetes: ★★★☆☆
    Flink: ★★★☆☆
    HTML+CSS: ★★★★☆
  # My Personal Labels
  labels:
    - 架构师
    - 全栈开发
    - Gopher
    - 大数据
    - 人工智能
    - 智能硬件
    - 机器人
  # My Personal Projects
  projects:
    📣 智能语音助手Kim: https://github.com/lesterlaucn/kim-voice-assistant
